version: '3.8'

services:
  mux-db:
    image: postgres:15-alpine
    container_name: mux_postgres
    restart: always
    environment:
      # 🚨 极重要：去掉 :-lab_password 这种默认兜底！
      # 逼迫自己必须从 .env 读取，防止密码泄露到历史记录
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    expose:
      - "5432" # 仅在容器局域网内可见，外部无法扫描，安全

  mux-backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: mux_backend
    restart: always
    depends_on:
      - mux-db
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@mux-db:5432/${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-1440}
    volumes:
      - ./server/uploads:/app/uploads
    expose:
      - "8000"

  mux-frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: mux_frontend
    restart: always
    expose:
      - "80"

  mux-nginx:
    image: nginx:stable-alpine
    container_name: mux_gateway
    restart: always
    ports:
      # 🚨 改为高位私有端口（例如 18080），绝不占用公共 80 端口   http://202.141.163.217:18080
      - "18080:80" 
    depends_on:
      - mux-backend
      - mux-frontend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  # 使用具有项目辨识度的卷名，防止和别人冲突
  postgres_prod_data: