#!/usr/bin/env bash
set -euo pipefail

# Must be run with the PostgreSQL bootstrap/owner account, never the web role.
db_container="$1"
db_name="$2"
owner_user="$3"
app_password="$4"
backup_password="$5"

# Credentials generated by deploy.sh are hexadecimal. Reject unsafe manual
# values rather than interpolating them into SQL.
if [[ ! "$owner_user" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || [[ ! "$app_password" =~ ^[A-Za-z0-9]+$ ]] || [[ ! "$backup_password" =~ ^[A-Za-z0-9]+$ ]]; then
  echo "Database owner and role passwords must use safe alphanumeric values."
  exit 1
fi

docker exec -i "$db_container" psql -v ON_ERROR_STOP=1 -U "$owner_user" -d "$db_name" <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'mux_app') THEN
    CREATE ROLE mux_app LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION PASSWORD '${app_password}';
  ELSE
    ALTER ROLE mux_app NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION PASSWORD '${app_password}';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'mux_backup') THEN
    CREATE ROLE mux_backup LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION PASSWORD '${backup_password}';
  ELSE
    ALTER ROLE mux_backup NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION PASSWORD '${backup_password}';
  END IF;
END \$\$;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO mux_app, mux_backup;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO mux_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO mux_app;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO mux_backup;
ALTER DEFAULT PRIVILEGES FOR ROLE ${owner_user} IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO mux_app;
ALTER DEFAULT PRIVILEGES FOR ROLE ${owner_user} IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO mux_app;
ALTER DEFAULT PRIVILEGES FOR ROLE ${owner_user} IN SCHEMA public GRANT SELECT ON TABLES TO mux_backup;
SQL
